# backend/scoring/embedder.py
#
# BGE-large cosine similarity.
# NOTE: We are NOT checking how close the answer is to a fixed "correct answer".
# We embed BOTH the candidate answer AND a set of key concepts expected for the
# question, then measure how much semantic overlap exists.
# This rewards correct understanding expressed in any words.

import numpy as np
from sentence_transformers import SentenceTransformer
from .config import EMBEDDING_MODEL

_model = None


def _get_model() -> SentenceTransformer:
    global _model
    if _model is None:
        print(f"[Embedder] Loading {EMBEDDING_MODEL} ...")
        _model = SentenceTransformer(EMBEDDING_MODEL)
        print("[Embedder] Ready.")
    return _model


def _embed(texts: list) -> np.ndarray:
    # BGE-large works best with this query prefix for similarity tasks
    prefixed = [
        f"Represent this sentence for searching relevant answers: {t}" for t in texts
    ]
    return _get_model().encode(prefixed, normalize_embeddings=True)


def concept_similarity(answer: str, key_concepts: str) -> float:
    """
    Measures how well the candidate's answer covers the key concepts
    expected for a question.

    key_concepts: a short paragraph describing what a correct answer
    should cover conceptually — generated by the LLM per question.
    This is NOT a model answer. It's a concept map.

    Returns 0.0–1.0.  Rewarded for covering the right IDEAS regardless
    of exact phrasing, terminology, or sentence structure.
    """
    if not answer.strip() or not key_concepts.strip():
        return 0.0

    vecs = _embed([answer, key_concepts])
    score = float(np.dot(vecs[0], vecs[1]))  # already normalized → cosine sim
    return round(max(0.0, min(1.0, score)), 4)
